# Generated by Django 6.0.3 on 2026-04-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('client_fidele', models.BooleanField(default=False, verbose_name='Client fidèle')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('poste', models.CharField(choices=[('caissier', 'Caissier'), ('gestionnaire_stock', 'Gestionnaire de stock'), ('manager', 'Manager'), ('vendeur', 'Vendeur'), ('agent_securite', 'Agent de sécurité')], max_length=50, verbose_name='Poste')),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Taux horaire (MAD)')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Employé actif')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.IntegerField(verbose_name='Quantité reçue')),
                ('fournisseur', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût total (MAD)')),
                ('reference_facture', models.CharField(blank=True, max_length=100, verbose_name='Référence facture')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('recu', 'Reçu'), ('annule', 'Annulé')], default='recu', max_length=20, verbose_name='Statut')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_travaillees', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Heures travaillées')),
                ('salaire_calcule', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire calculé (MAD)')),
                ('mois', models.CharField(max_length=20, verbose_name='Mois (AAAA-MM)')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Paie',
                'verbose_name_plural': 'Paies',
                'ordering': ['-mois', 'employe'],
                'unique_together': {('employe', 'mois')},
            },
        ),
    ]
