# Generated by Django 6.0.3 on 2026-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (MAD)')),
                ('quantite_stock', models.IntegerField(verbose_name='Quantité en stock')),
                ('seuil_alerte', models.IntegerField(default=10, verbose_name="Seuil d'alerte de stock")),
                ('categorie', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(verbose_name='Quantité vendue')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (MAD)')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total (MAD)')),
                ('date_vente', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('statut', models.CharField(choices=[('validée', 'Validée'), ('annulée', 'Annulée'), ('en_cours', 'En cours')], default='validée', max_length=20, verbose_name='Statut')),
                ('numero_transaction', models.CharField(max_length=50, unique=True, verbose_name='Numéro de transaction')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
    ]
