# Generated by Django 6.0.3 on 2026-04-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0001_initial'),
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caisse.produit', verbose_name='Produit'),
        ),
    ]
