# Generated by Django 6.0.3 on 2026-04-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='numero_transaction',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de transaction'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='prix_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix total (MAD)'),
        ),
    ]
